/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proverbsapp;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;

/**
 *
 * @author Janey
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Parent = new javax.swing.JPanel();
        StartPage = new javax.swing.JPanel();
        Start = new javax.swing.JButton();
        volOff = new javax.swing.JButton();
        volOn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MainMenu = new javax.swing.JPanel();
        backToStart = new javax.swing.JButton();
        Dev = new javax.swing.JButton();
        Author = new javax.swing.JButton();
        Twenty6to31 = new javax.swing.JButton();
        Twenty1to25 = new javax.swing.JButton();
        Sixteento20 = new javax.swing.JButton();
        Elevento15 = new javax.swing.JButton();
        SixtoTen = new javax.swing.JButton();
        OnetoFive = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Page1 = new javax.swing.JPanel();
        Main1 = new javax.swing.JButton();
        p1Keyword = new javax.swing.JTextField();
        p1Verse = new javax.swing.JTextField();
        p1Chapter = new javax.swing.JTextField();
        searchCV1 = new javax.swing.JButton();
        searchK1 = new javax.swing.JButton();
        Page1verse = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Page2 = new javax.swing.JPanel();
        Main2 = new javax.swing.JButton();
        p2Keyword = new javax.swing.JTextField();
        p2Verse = new javax.swing.JTextField();
        p2Chapter = new javax.swing.JTextField();
        searchCV2 = new javax.swing.JButton();
        searchK2 = new javax.swing.JButton();
        Page2verse = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Page3 = new javax.swing.JPanel();
        Main3 = new javax.swing.JButton();
        p3Keyword = new javax.swing.JTextField();
        p3Verse = new javax.swing.JTextField();
        p3Chapter = new javax.swing.JTextField();
        searchCV3 = new javax.swing.JButton();
        searchK3 = new javax.swing.JButton();
        Page3verse = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Page4 = new javax.swing.JPanel();
        Main4 = new javax.swing.JButton();
        p4Keyword = new javax.swing.JTextField();
        p4Verse = new javax.swing.JTextField();
        p4Chapter = new javax.swing.JTextField();
        searchCV4 = new javax.swing.JButton();
        searchK4 = new javax.swing.JButton();
        Page4verse = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Page5 = new javax.swing.JPanel();
        Main5 = new javax.swing.JButton();
        p5Keyword = new javax.swing.JTextField();
        p5Verse = new javax.swing.JTextField();
        p5Chapter = new javax.swing.JTextField();
        searchCV5 = new javax.swing.JButton();
        searchK5 = new javax.swing.JButton();
        Page5verse = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Page6 = new javax.swing.JPanel();
        Main6 = new javax.swing.JButton();
        p6Keyword = new javax.swing.JTextField();
        p6Verse = new javax.swing.JTextField();
        p6Chapter = new javax.swing.JTextField();
        searchCV6 = new javax.swing.JButton();
        searchK6 = new javax.swing.JButton();
        Page6verse = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        AuthorPage = new javax.swing.JPanel();
        MainFromAuthor = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        DevPage = new javax.swing.JPanel();
        MainFromDev = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Parent.setBackground(new java.awt.Color(160, 141, 141));
        Parent.setLayout(new java.awt.CardLayout());

        StartPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Start.setBackground(new java.awt.Color(102, 51, 0));
        Start.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        Start.setForeground(new java.awt.Color(255, 255, 255));
        Start.setText("Start Reading");
        Start.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Start.setBorderPainted(false);
        Start.setFocusPainted(false);
        Start.setRolloverEnabled(false);
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });
        StartPage.add(Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 110, 30));

        volOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/volume-down.png"))); // NOI18N
        volOff.setBorderPainted(false);
        volOff.setContentAreaFilled(false);
        volOff.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        volOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volOffActionPerformed(evt);
            }
        });
        StartPage.add(volOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 40, 30));

        volOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/volume-up.png"))); // NOI18N
        volOn.setBorderPainted(false);
        volOn.setContentAreaFilled(false);
        volOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volOnActionPerformed(evt);
            }
        });
        StartPage.add(volOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 40, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1.png"))); // NOI18N
        StartPage.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Parent.add(StartPage, "card2");

        MainMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backToStart.setBackground(new java.awt.Color(102, 51, 0));
        backToStart.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        backToStart.setForeground(new java.awt.Color(255, 255, 255));
        backToStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/turn-back.png"))); // NOI18N
        backToStart.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backToStart.setBorderPainted(false);
        backToStart.setContentAreaFilled(false);
        backToStart.setFocusPainted(false);
        backToStart.setRolloverEnabled(false);
        backToStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToStartActionPerformed(evt);
            }
        });
        MainMenu.add(backToStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 40, 30));

        Dev.setBackground(new java.awt.Color(102, 51, 0));
        Dev.setFont(new java.awt.Font("Sitka Text", 1, 23)); // NOI18N
        Dev.setText("DEVELOPER");
        Dev.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Dev.setBorderPainted(false);
        Dev.setContentAreaFilled(false);
        Dev.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Dev.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Dev.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Dev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevActionPerformed(evt);
            }
        });
        MainMenu.add(Dev, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 160, 40));

        Author.setBackground(new java.awt.Color(102, 51, 0));
        Author.setFont(new java.awt.Font("Sitka Text", 1, 23)); // NOI18N
        Author.setText("AUTHOR");
        Author.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Author.setBorderPainted(false);
        Author.setContentAreaFilled(false);
        Author.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Author.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Author.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorActionPerformed(evt);
            }
        });
        MainMenu.add(Author, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 130, 40));

        Twenty6to31.setBackground(new java.awt.Color(102, 51, 0));
        Twenty6to31.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        Twenty6to31.setText("26 . . . . . 31");
        Twenty6to31.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Twenty6to31.setBorderPainted(false);
        Twenty6to31.setContentAreaFilled(false);
        Twenty6to31.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Twenty6to31.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Twenty6to31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Twenty6to31ActionPerformed(evt);
            }
        });
        MainMenu.add(Twenty6to31, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 130, 30));

        Twenty1to25.setBackground(new java.awt.Color(102, 51, 0));
        Twenty1to25.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        Twenty1to25.setText("21 . . . . . 25");
        Twenty1to25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Twenty1to25.setBorderPainted(false);
        Twenty1to25.setContentAreaFilled(false);
        Twenty1to25.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Twenty1to25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Twenty1to25ActionPerformed(evt);
            }
        });
        MainMenu.add(Twenty1to25, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 130, 30));

        Sixteento20.setBackground(new java.awt.Color(102, 51, 0));
        Sixteento20.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        Sixteento20.setText("16 . . . . . 20");
        Sixteento20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Sixteento20.setBorderPainted(false);
        Sixteento20.setContentAreaFilled(false);
        Sixteento20.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Sixteento20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Sixteento20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sixteento20ActionPerformed(evt);
            }
        });
        MainMenu.add(Sixteento20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 130, 30));

        Elevento15.setBackground(new java.awt.Color(102, 51, 0));
        Elevento15.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        Elevento15.setText("11 . . . . . 15");
        Elevento15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Elevento15.setBorderPainted(false);
        Elevento15.setContentAreaFilled(false);
        Elevento15.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Elevento15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Elevento15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Elevento15ActionPerformed(evt);
            }
        });
        MainMenu.add(Elevento15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 130, 30));

        SixtoTen.setBackground(new java.awt.Color(102, 51, 0));
        SixtoTen.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        SixtoTen.setText("6 . . . . . 10");
        SixtoTen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SixtoTen.setBorderPainted(false);
        SixtoTen.setContentAreaFilled(false);
        SixtoTen.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SixtoTen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SixtoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixtoTenActionPerformed(evt);
            }
        });
        MainMenu.add(SixtoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 130, 30));

        OnetoFive.setBackground(new java.awt.Color(102, 51, 0));
        OnetoFive.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        OnetoFive.setText("1 . . . . . 5");
        OnetoFive.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OnetoFive.setBorderPainted(false);
        OnetoFive.setContentAreaFilled(false);
        OnetoFive.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        OnetoFive.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        OnetoFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnetoFiveActionPerformed(evt);
            }
        });
        MainMenu.add(OnetoFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 130, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/2.png"))); // NOI18N
        MainMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Parent.add(MainMenu, "card3");

        Page1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Main1.setBackground(new java.awt.Color(102, 51, 0));
        Main1.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        Main1.setForeground(new java.awt.Color(255, 255, 255));
        Main1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/turn-back.png"))); // NOI18N
        Main1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Main1.setBorderPainted(false);
        Main1.setContentAreaFilled(false);
        Main1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main1ActionPerformed(evt);
            }
        });
        Page1.add(Main1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 40, 30));

        p1Keyword.setBackground(new java.awt.Color(255, 255, 255, 0));
        p1Keyword.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        p1Keyword.setForeground(new java.awt.Color(255, 255, 255));
        p1Keyword.setText("Enter Keyword ...");
        p1Keyword.setBorder(null);
        Page1.add(p1Keyword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 270, 60));

        p1Verse.setBackground(new java.awt.Color(255, 255, 255, 0));
        p1Verse.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        p1Verse.setForeground(new java.awt.Color(255, 255, 255));
        p1Verse.setText("Enter Verse");
        p1Verse.setBorder(null);
        Page1.add(p1Verse, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 120, 30));

        p1Chapter.setBackground(new java.awt.Color(255, 255, 255, 0));
        p1Chapter.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        p1Chapter.setForeground(new java.awt.Color(255, 255, 255));
        p1Chapter.setText("Enter Chapter");
        p1Chapter.setBorder(null);
        Page1.add(p1Chapter, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 120, 30));

        searchCV1.setBackground(new java.awt.Color(102, 51, 0));
        searchCV1.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        searchCV1.setForeground(new java.awt.Color(255, 255, 255));
        searchCV1.setText("Search Chapter/Verse");
        searchCV1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchCV1.setBorderPainted(false);
        searchCV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCV1ActionPerformed(evt);
            }
        });
        Page1.add(searchCV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 170, 20));

        searchK1.setBackground(new java.awt.Color(102, 51, 0));
        searchK1.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        searchK1.setForeground(new java.awt.Color(255, 255, 255));
        searchK1.setText("Search Verse through Keyword");
        searchK1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchK1.setBorderPainted(false);
        searchK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchK1ActionPerformed(evt);
            }
        });
        Page1.add(searchK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 200, 20));

        Page1verse.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        Page1verse.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Page1.add(Page1verse, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 600, 120));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/3.png"))); // NOI18N
        Page1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Parent.add(Page1, "card4");

        Page2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Main2.setBackground(new java.awt.Color(102, 51, 0));
        Main2.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        Main2.setForeground(new java.awt.Color(255, 255, 255));
        Main2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/turn-back.png"))); // NOI18N
        Main2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Main2.setBorderPainted(false);
        Main2.setContentAreaFilled(false);
        Main2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main2ActionPerformed(evt);
            }
        });
        Page2.add(Main2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 40, 30));

        p2Keyword.setBackground(new java.awt.Color(255, 255, 255, 0));
        p2Keyword.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        p2Keyword.setForeground(new java.awt.Color(255, 255, 255));
        p2Keyword.setText("Enter Keyword ...");
        p2Keyword.setBorder(null);
        Page2.add(p2Keyword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 270, 60));

        p2Verse.setBackground(new java.awt.Color(255, 255, 255, 0));
        p2Verse.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        p2Verse.setForeground(new java.awt.Color(255, 255, 255));
        p2Verse.setText("Enter Verse");
        p2Verse.setBorder(null);
        Page2.add(p2Verse, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 120, 30));

        p2Chapter.setBackground(new java.awt.Color(255, 255, 255, 0));
        p2Chapter.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        p2Chapter.setForeground(new java.awt.Color(255, 255, 255));
        p2Chapter.setText("Enter Chapter");
        p2Chapter.setBorder(null);
        Page2.add(p2Chapter, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 120, 30));

        searchCV2.setBackground(new java.awt.Color(102, 51, 0));
        searchCV2.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        searchCV2.setForeground(new java.awt.Color(255, 255, 255));
        searchCV2.setText("Search Chapter/Verse");
        searchCV2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchCV2.setBorderPainted(false);
        searchCV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCV2ActionPerformed(evt);
            }
        });
        Page2.add(searchCV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 170, 20));

        searchK2.setBackground(new java.awt.Color(102, 51, 0));
        searchK2.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        searchK2.setForeground(new java.awt.Color(255, 255, 255));
        searchK2.setText("Search Verse through Keyword");
        searchK2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchK2.setBorderPainted(false);
        searchK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchK2ActionPerformed(evt);
            }
        });
        Page2.add(searchK2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 200, 20));

        Page2verse.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        Page2verse.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Page2.add(Page2verse, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 600, 120));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/4.png"))); // NOI18N
        Page2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Parent.add(Page2, "card5");

        Page3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Main3.setBackground(new java.awt.Color(102, 51, 0));
        Main3.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        Main3.setForeground(new java.awt.Color(255, 255, 255));
        Main3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/turn-back.png"))); // NOI18N
        Main3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Main3.setBorderPainted(false);
        Main3.setContentAreaFilled(false);
        Main3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main3ActionPerformed(evt);
            }
        });
        Page3.add(Main3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 40, 30));

        p3Keyword.setBackground(new java.awt.Color(255, 255, 255, 0));
        p3Keyword.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        p3Keyword.setForeground(new java.awt.Color(255, 255, 255));
        p3Keyword.setText("Enter Keyword ...");
        p3Keyword.setBorder(null);
        Page3.add(p3Keyword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 270, 60));

        p3Verse.setBackground(new java.awt.Color(255, 255, 255, 0));
        p3Verse.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        p3Verse.setForeground(new java.awt.Color(255, 255, 255));
        p3Verse.setText("Enter Verse");
        p3Verse.setBorder(null);
        Page3.add(p3Verse, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 120, 30));

        p3Chapter.setBackground(new java.awt.Color(255, 255, 255, 0));
        p3Chapter.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        p3Chapter.setForeground(new java.awt.Color(255, 255, 255));
        p3Chapter.setText("Enter Chapter");
        p3Chapter.setBorder(null);
        Page3.add(p3Chapter, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 120, 30));

        searchCV3.setBackground(new java.awt.Color(102, 51, 0));
        searchCV3.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        searchCV3.setForeground(new java.awt.Color(255, 255, 255));
        searchCV3.setText("Search Chapter/Verse");
        searchCV3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchCV3.setBorderPainted(false);
        searchCV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCV3ActionPerformed(evt);
            }
        });
        Page3.add(searchCV3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 170, 20));

        searchK3.setBackground(new java.awt.Color(102, 51, 0));
        searchK3.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        searchK3.setForeground(new java.awt.Color(255, 255, 255));
        searchK3.setText("Search Verse through Keyword");
        searchK3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchK3.setBorderPainted(false);
        searchK3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchK3ActionPerformed(evt);
            }
        });
        Page3.add(searchK3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 200, 20));

        Page3verse.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        Page3verse.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Page3.add(Page3verse, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 600, 120));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/5.png"))); // NOI18N
        Page3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Parent.add(Page3, "card6");

        Page4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Main4.setBackground(new java.awt.Color(102, 51, 0));
        Main4.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        Main4.setForeground(new java.awt.Color(255, 255, 255));
        Main4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/turn-back.png"))); // NOI18N
        Main4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Main4.setBorderPainted(false);
        Main4.setContentAreaFilled(false);
        Main4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main4ActionPerformed(evt);
            }
        });
        Page4.add(Main4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 40, 30));

        p4Keyword.setBackground(new java.awt.Color(255, 255, 255, 0));
        p4Keyword.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        p4Keyword.setForeground(new java.awt.Color(255, 255, 255));
        p4Keyword.setText("Enter Keyword ...");
        p4Keyword.setBorder(null);
        Page4.add(p4Keyword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 270, 60));

        p4Verse.setBackground(new java.awt.Color(255, 255, 255, 0));
        p4Verse.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        p4Verse.setForeground(new java.awt.Color(255, 255, 255));
        p4Verse.setText("Enter Verse");
        p4Verse.setBorder(null);
        Page4.add(p4Verse, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 120, 30));

        p4Chapter.setBackground(new java.awt.Color(255, 255, 255, 0));
        p4Chapter.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        p4Chapter.setForeground(new java.awt.Color(255, 255, 255));
        p4Chapter.setText("Enter Chapter");
        p4Chapter.setBorder(null);
        Page4.add(p4Chapter, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 120, 30));

        searchCV4.setBackground(new java.awt.Color(102, 51, 0));
        searchCV4.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        searchCV4.setForeground(new java.awt.Color(255, 255, 255));
        searchCV4.setText("Search Chapter/Verse");
        searchCV4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchCV4.setBorderPainted(false);
        searchCV4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCV4ActionPerformed(evt);
            }
        });
        Page4.add(searchCV4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 170, 20));

        searchK4.setBackground(new java.awt.Color(102, 51, 0));
        searchK4.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        searchK4.setForeground(new java.awt.Color(255, 255, 255));
        searchK4.setText("Search Verse through Keyword");
        searchK4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchK4.setBorderPainted(false);
        searchK4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchK4ActionPerformed(evt);
            }
        });
        Page4.add(searchK4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 200, 20));

        Page4verse.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        Page4verse.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Page4.add(Page4verse, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 600, 120));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/6.png"))); // NOI18N
        Page4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Parent.add(Page4, "card7");

        Page5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Main5.setBackground(new java.awt.Color(102, 51, 0));
        Main5.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        Main5.setForeground(new java.awt.Color(255, 255, 255));
        Main5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/turn-back.png"))); // NOI18N
        Main5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Main5.setBorderPainted(false);
        Main5.setContentAreaFilled(false);
        Main5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main5ActionPerformed(evt);
            }
        });
        Page5.add(Main5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 40, 30));

        p5Keyword.setBackground(new java.awt.Color(255, 255, 255, 0));
        p5Keyword.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        p5Keyword.setForeground(new java.awt.Color(255, 255, 255));
        p5Keyword.setText("Enter Keyword ...");
        p5Keyword.setBorder(null);
        Page5.add(p5Keyword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 270, 60));

        p5Verse.setBackground(new java.awt.Color(255, 255, 255, 0));
        p5Verse.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        p5Verse.setForeground(new java.awt.Color(255, 255, 255));
        p5Verse.setText("Enter Verse");
        p5Verse.setBorder(null);
        Page5.add(p5Verse, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 120, 30));

        p5Chapter.setBackground(new java.awt.Color(255, 255, 255, 0));
        p5Chapter.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        p5Chapter.setForeground(new java.awt.Color(255, 255, 255));
        p5Chapter.setText("Enter Chapter");
        p5Chapter.setBorder(null);
        Page5.add(p5Chapter, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 120, 30));

        searchCV5.setBackground(new java.awt.Color(102, 51, 0));
        searchCV5.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        searchCV5.setForeground(new java.awt.Color(255, 255, 255));
        searchCV5.setText("Search Chapter/Verse");
        searchCV5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchCV5.setBorderPainted(false);
        searchCV5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCV5ActionPerformed(evt);
            }
        });
        Page5.add(searchCV5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 170, 20));

        searchK5.setBackground(new java.awt.Color(102, 51, 0));
        searchK5.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        searchK5.setForeground(new java.awt.Color(255, 255, 255));
        searchK5.setText("Search Verse through Keyword");
        searchK5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchK5.setBorderPainted(false);
        searchK5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchK5ActionPerformed(evt);
            }
        });
        Page5.add(searchK5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 200, 20));

        Page5verse.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        Page5verse.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Page5.add(Page5verse, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 600, 120));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/7.png"))); // NOI18N
        Page5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Parent.add(Page5, "card8");

        Page6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Main6.setBackground(new java.awt.Color(102, 51, 0));
        Main6.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        Main6.setForeground(new java.awt.Color(255, 255, 255));
        Main6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/turn-back.png"))); // NOI18N
        Main6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Main6.setBorderPainted(false);
        Main6.setContentAreaFilled(false);
        Main6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main6ActionPerformed(evt);
            }
        });
        Page6.add(Main6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 40, 30));

        p6Keyword.setBackground(new java.awt.Color(255, 255, 255, 0));
        p6Keyword.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        p6Keyword.setForeground(new java.awt.Color(255, 255, 255));
        p6Keyword.setText("Enter Keyword ...");
        p6Keyword.setBorder(null);
        Page6.add(p6Keyword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 270, 60));

        p6Verse.setBackground(new java.awt.Color(255, 255, 255, 0));
        p6Verse.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        p6Verse.setForeground(new java.awt.Color(255, 255, 255));
        p6Verse.setText("Enter Verse");
        p6Verse.setBorder(null);
        Page6.add(p6Verse, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 120, 30));

        p6Chapter.setBackground(new java.awt.Color(255, 255, 255, 0));
        p6Chapter.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        p6Chapter.setForeground(new java.awt.Color(255, 255, 255));
        p6Chapter.setText("Enter Chapter");
        p6Chapter.setBorder(null);
        Page6.add(p6Chapter, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 120, 30));

        searchCV6.setBackground(new java.awt.Color(102, 51, 0));
        searchCV6.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        searchCV6.setForeground(new java.awt.Color(255, 255, 255));
        searchCV6.setText("Search Chapter/Verse");
        searchCV6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchCV6.setBorderPainted(false);
        searchCV6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCV6ActionPerformed(evt);
            }
        });
        Page6.add(searchCV6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 170, 20));

        searchK6.setBackground(new java.awt.Color(102, 51, 0));
        searchK6.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        searchK6.setForeground(new java.awt.Color(255, 255, 255));
        searchK6.setText("Search Verse through Keyword");
        searchK6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchK6.setBorderPainted(false);
        searchK6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchK6ActionPerformed(evt);
            }
        });
        Page6.add(searchK6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 200, 20));

        Page6verse.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        Page6verse.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Page6.add(Page6verse, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 600, 120));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/8.png"))); // NOI18N
        Page6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Parent.add(Page6, "card9");

        AuthorPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainFromAuthor.setBackground(new java.awt.Color(102, 51, 0));
        MainFromAuthor.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        MainFromAuthor.setForeground(new java.awt.Color(255, 255, 255));
        MainFromAuthor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/turn-back.png"))); // NOI18N
        MainFromAuthor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MainFromAuthor.setBorderPainted(false);
        MainFromAuthor.setContentAreaFilled(false);
        MainFromAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainFromAuthorActionPerformed(evt);
            }
        });
        AuthorPage.add(MainFromAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 40, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/9.png"))); // NOI18N
        AuthorPage.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Parent.add(AuthorPage, "card10");

        DevPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainFromDev.setBackground(new java.awt.Color(102, 51, 0));
        MainFromDev.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        MainFromDev.setForeground(new java.awt.Color(255, 255, 255));
        MainFromDev.setText("Main");
        MainFromDev.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MainFromDev.setBorderPainted(false);
        MainFromDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainFromDevActionPerformed(evt);
            }
        });
        DevPage.add(MainFromDev, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 70, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/10.png"))); // NOI18N
        DevPage.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Parent.add(DevPage, "card11");

        getContentPane().add(Parent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Page jumps from table of contents: BEGIN
    public static VerseAVLTree tree1, tree2, tree3, tree4, tree5, tree6;
    
    private void SixtoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixtoTenActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(Page2);
        Parent.repaint();
        Parent.revalidate();
        
        tree2 = VerseFileHandling.readVersesFromFile("src\\Proverbs6to10.txt");
    }//GEN-LAST:event_SixtoTenActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(MainMenu);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_StartActionPerformed

    private void OnetoFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnetoFiveActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(Page1);
        Parent.repaint();
        Parent.revalidate();
        
        tree1 = VerseFileHandling.readVersesFromFile("src\\Proverbs1to5.txt");
    }//GEN-LAST:event_OnetoFiveActionPerformed

    private void Elevento15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Elevento15ActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(Page3);
        Parent.repaint();
        Parent.revalidate();
        
        tree3 = VerseFileHandling.readVersesFromFile("src\\Proverbs11to15.txt");
    }//GEN-LAST:event_Elevento15ActionPerformed

    private void Sixteento20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sixteento20ActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(Page4);
        Parent.repaint();
        Parent.revalidate();
        
        tree4 = VerseFileHandling.readVersesFromFile("src\\Proverbs16to20.txt");
    }//GEN-LAST:event_Sixteento20ActionPerformed

    private void Twenty1to25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Twenty1to25ActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(Page5);
        Parent.repaint();
        Parent.revalidate();
        
        tree5 = VerseFileHandling.readVersesFromFile("src\\Proverbs21to25.txt");
    }//GEN-LAST:event_Twenty1to25ActionPerformed

    private void Twenty6to31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Twenty6to31ActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(Page6);
        Parent.repaint();
        Parent.revalidate();
        
        tree6 = VerseFileHandling.readVersesFromFile("src\\Proverbs26to31.txt");
    }//GEN-LAST:event_Twenty6to31ActionPerformed

    private void AuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(AuthorPage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_AuthorActionPerformed

    private void DevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(DevPage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_DevActionPerformed
    //Page jumps from table of contents: END
    
    
    //Page buttons return to Main Table of Contents: BEGIN
    private void Main1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main1ActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(MainMenu);
        Parent.repaint();
        Parent.revalidate();
        
        tree1.makeEmpty();
        p1Chapter.setText("Enter Chapter");
        p1Verse.setText("Enter Verse");
        p1Keyword.setText("Enter Keyword ...");
        Page1verse.setText("");
    }//GEN-LAST:event_Main1ActionPerformed

    private void Main2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main2ActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(MainMenu);
        Parent.repaint();
        Parent.revalidate();
        
        tree2.makeEmpty();
        p2Chapter.setText("Enter Chapter");
        p2Verse.setText("Enter Verse");
        p2Keyword.setText("Enter Keyword ...");
        Page2verse.setText("");
    }//GEN-LAST:event_Main2ActionPerformed

    private void Main3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main3ActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(MainMenu);
        Parent.repaint();
        Parent.revalidate();
        
        tree3.makeEmpty();
        p3Chapter.setText("Enter Chapter");
        p3Verse.setText("Enter Verse");
        p3Keyword.setText("Enter Keyword ...");
        Page3verse.setText("");
    }//GEN-LAST:event_Main3ActionPerformed

    private void Main4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main4ActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(MainMenu);
        Parent.repaint();
        Parent.revalidate();
        
        tree4.makeEmpty();
        p4Chapter.setText("Enter Chapter");
        p4Verse.setText("Enter Verse");
        p4Keyword.setText("Enter Keyword ...");
        Page4verse.setText("");
    }//GEN-LAST:event_Main4ActionPerformed

    private void Main5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main5ActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(MainMenu);
        Parent.repaint();
        Parent.revalidate();
        
        tree5.makeEmpty();
        p5Chapter.setText("Enter Chapter");
        p5Verse.setText("Enter Verse");
        p5Keyword.setText("Enter Keyword ...");
        Page5verse.setText("");
    }//GEN-LAST:event_Main5ActionPerformed

    private void Main6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main6ActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(MainMenu);
        Parent.repaint();
        Parent.revalidate();
        
        tree6.makeEmpty();
        p6Chapter.setText("Enter Chapter");
        p6Verse.setText("Enter Verse");
        p6Keyword.setText("Enter Keyword ...");
        Page6verse.setText("");
    }//GEN-LAST:event_Main6ActionPerformed

    private void MainFromAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainFromAuthorActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(MainMenu);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_MainFromAuthorActionPerformed

    private void MainFromDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainFromDevActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(MainMenu);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_MainFromDevActionPerformed
    //Page buttons return to Main Table of Contents: END
    
    //Page jump from Table of Contents to Start Page
    private void backToStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToStartActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(StartPage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_backToStartActionPerformed

    
    //Music Options: BEGIN
    private static Clip clip;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            AudioInputStream austr = AudioSystem.getAudioInputStream(getClass().getResource("Agnus Dei.wav"));
            clip = AudioSystem.getClip();
            clip.open(austr);
            clip.start();
            clip.loop(Clip.LOOP_CONTINUOUSLY);
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private static long clipTimePosition;
    private void volOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volOnActionPerformed
        // TODO add your handling code here:
        clip.setMicrosecondPosition(clipTimePosition);
        clip.start();
        clipTimePosition = 0;
    }//GEN-LAST:event_volOnActionPerformed

    private void volOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volOffActionPerformed
        // TODO add your handling code here:
        clipTimePosition = clip.getMicrosecondPosition();
        clip.stop();
    }//GEN-LAST:event_volOffActionPerformed
    //Music Options: END
    
    
    //Search Actions: BEGIN
    private void searchCV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCV1ActionPerformed
        // TODO add your handling code here:
        if(!p1Keyword.getText().isBlank()){
            p1Keyword.setText("Enter Keyword ...");
        }
        
        int chapter, verse;
        try{
            chapter = Integer.parseInt(p1Chapter.getText());
            verse = Integer.parseInt(p1Verse.getText());
            
            try{
                VerseNode found = tree1.searchNode(chapter,verse, tree1.getRoot());
                Page1verse.setText(found.toString());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error! Verse does not exist in this page.", "Proverbs App: Output Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error! Chapter/Verse is blank.", "Proverbs App: Input Error.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchCV1ActionPerformed

    private void searchK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchK1ActionPerformed
        // TODO add your handling code here:
        if(!p1Chapter.getText().isBlank() && !p1Verse.getText().isBlank()){
            p1Chapter.setText("Enter Chapter");
            p1Verse.setText("Enter Verse");
        }
        
        if(!p1Keyword.getText().isBlank() && !p1Keyword.getText().equals("Enter Keyword ...")){
            try{
                VerseNode found = tree1.searchNodeByKeyword(p1Keyword.getText(), tree1.getRoot());
                Page1verse.setText(found.toString());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error! Verse does not exist in this page.", "Proverbs App: Output Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Error! Keyword is blank.", "Proverbs App: Input Error.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchK1ActionPerformed

    private void searchCV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCV2ActionPerformed
        // TODO add your handling code here:
        if(!p2Keyword.getText().isBlank()){
            p2Keyword.setText("Enter Keyword ...");
        }
        
        int chapter, verse;
        try{
            chapter = Integer.parseInt(p2Chapter.getText());
            verse = Integer.parseInt(p2Verse.getText());
            
            try{
                VerseNode found = tree2.searchNode(chapter,verse, tree2.getRoot());
                Page2verse.setText(found.toString());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error! Verse does not exist in this page.", "Proverbs App: Output Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error! Chapter/Verse is blank.", "Proverbs App: Input Error.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchCV2ActionPerformed

    private void searchK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchK2ActionPerformed
        // TODO add your handling code here:
        if(!p2Chapter.getText().isBlank() && !p2Verse.getText().isBlank()){
            p2Chapter.setText("Enter Chapter");
            p2Verse.setText("Enter Chapter");
        }
        
        if(!p2Keyword.getText().isBlank() && !p2Keyword.getText().equals("Enter Keyword ...")){
            try{
                VerseNode found = tree2.searchNodeByKeyword(p2Keyword.getText(), tree2.getRoot());
                Page2verse.setText(found.toString());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error! Verse does not exist in this page.", "Proverbs App: Output Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Error! Keyword is blank.", "Proverbs App: Input Error.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchK2ActionPerformed

    private void searchCV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCV3ActionPerformed
        // TODO add your handling code here:
        if(!p3Keyword.getText().isBlank()){
            p3Keyword.setText("Enter Keyword ...");
        }
        
        int chapter, verse;
        try{
            chapter = Integer.parseInt(p3Chapter.getText());
            verse = Integer.parseInt(p3Verse.getText());
            
            try{
                VerseNode found = tree3.searchNode(chapter,verse, tree3.getRoot());
                Page3verse.setText(found.toString());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error! Verse does not exist in this page.", "Proverbs App: Output Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error! Chapter/Verse is blank.", "Proverbs App: Input Error.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchCV3ActionPerformed

    private void searchK3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchK3ActionPerformed
        // TODO add your handling code here:
        if(!p3Chapter.getText().isBlank() && !p3Verse.getText().isBlank()){
            p3Chapter.setText("Enter Chapter");
            p3Verse.setText("Enter Verse");
        }
        
        if(!p3Keyword.getText().isBlank() && !p3Keyword.getText().equals("Enter Keyword ...")){
            try{
                VerseNode found = tree3.searchNodeByKeyword(p3Keyword.getText(), tree3.getRoot());
                Page3verse.setText(found.toString());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error! Verse does not exist in this page.", "Proverbs App: Output Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Error! Keyword is blank.", "Proverbs App: Input Error.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchK3ActionPerformed

    private void searchCV4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCV4ActionPerformed
        // TODO add your handling code here:
        if(!p4Keyword.getText().isBlank()){
            p4Keyword.setText("Enter Keyword ...");
        }
        
        int chapter, verse;
        try{
            chapter = Integer.parseInt(p4Chapter.getText());
            verse = Integer.parseInt(p4Verse.getText());
            
            try{
                VerseNode found = tree4.searchNode(chapter,verse, tree4.getRoot());
                Page4verse.setText(found.toString());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error! Verse does not exist in this page.", "Proverbs App: Output Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error! Chapter/Verse is blank.", "Proverbs App: Input Error.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchCV4ActionPerformed

    private void searchK4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchK4ActionPerformed
        // TODO add your handling code here:
        if(!p4Chapter.getText().isBlank() && !p4Verse.getText().isBlank()){
            p4Chapter.setText("Enter Chapter");
            p4Verse.setText("Enter Verse");
        }
        
        if(!p4Keyword.getText().isBlank() && !p4Keyword.getText().equals("Enter Keyword ...")){
            try{
                VerseNode found = tree4.searchNodeByKeyword(p4Keyword.getText(), tree4.getRoot());
                Page4verse.setText(found.toString());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error! Verse does not exist in this page.", "Proverbs App: Output Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Error! Keyword is blank.", "Proverbs App: Input Error.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchK4ActionPerformed

    private void searchCV5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCV5ActionPerformed
        // TODO add your handling code here:
        if(!p5Keyword.getText().isBlank()){
            p5Keyword.setText("Enter Keyword ...");
        }
        
        int chapter, verse;
        try{
            chapter = Integer.parseInt(p5Chapter.getText());
            verse = Integer.parseInt(p5Verse.getText());
            
            try{
                VerseNode found = tree5.searchNode(chapter,verse, tree5.getRoot());
                Page5verse.setText(found.toString());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error! Verse does not exist in this page.", "Proverbs App: Output Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error! Chapter/Verse is blank.", "Proverbs App: Input Error.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchCV5ActionPerformed

    private void searchK5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchK5ActionPerformed
        // TODO add your handling code here:
        if(!p5Chapter.getText().isBlank() && !p5Verse.getText().isBlank()){
            p5Chapter.setText("Enter Chapter");
            p5Verse.setText("Enter Verse");
        }
        
        if(!p5Keyword.getText().isBlank() && !p5Keyword.getText().equals("Enter Keyword ...")){
            try{
                VerseNode found = tree5.searchNodeByKeyword(p5Keyword.getText(), tree5.getRoot());
                Page5verse.setText(found.toString());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error! Verse does not exist in this page.", "Proverbs App: Output Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Error! Keyword is blank.", "Proverbs App: Input Error.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchK5ActionPerformed

    private void searchCV6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCV6ActionPerformed
        // TODO add your handling code here:
        if(!p6Keyword.getText().isBlank()){
            p6Keyword.setText("Enter Keyword ...");
        }
        
        int chapter, verse;
        try{
            chapter = Integer.parseInt(p6Chapter.getText());
            verse = Integer.parseInt(p6Verse.getText());
            
            try{
                VerseNode found = tree6.searchNode(chapter,verse, tree6.getRoot());
                Page6verse.setText(found.toString());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error! Verse does not exist in this page.", "Proverbs App: Output Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error! Chapter/Verse is blank.", "Proverbs App: Input Error.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchCV6ActionPerformed

    private void searchK6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchK6ActionPerformed
        // TODO add your handling code here:
        if(!p6Chapter.getText().isBlank() && !p6Verse.getText().isBlank()){
            p6Chapter.setText("Enter Chapter");
            p6Verse.setText("Enter Verse");
        }
        
        if(!p6Keyword.getText().isBlank() && !p6Keyword.getText().equals("Enter Keyword ...")){
            try{
                VerseNode found = tree6.searchNodeByKeyword(p6Keyword.getText(), tree6.getRoot());
                Page6verse.setText(found.toString());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error! Verse does not exist in this page.", "Proverbs App: Output Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Error! Keyword is blank.", "Proverbs App: Input Error.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchK6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Author;
    private javax.swing.JPanel AuthorPage;
    private javax.swing.JButton Dev;
    private javax.swing.JPanel DevPage;
    private javax.swing.JButton Elevento15;
    private javax.swing.JButton Main1;
    private javax.swing.JButton Main2;
    private javax.swing.JButton Main3;
    private javax.swing.JButton Main4;
    private javax.swing.JButton Main5;
    private javax.swing.JButton Main6;
    private javax.swing.JButton MainFromAuthor;
    private javax.swing.JButton MainFromDev;
    private javax.swing.JPanel MainMenu;
    private javax.swing.JButton OnetoFive;
    private javax.swing.JPanel Page1;
    private javax.swing.JLabel Page1verse;
    private javax.swing.JPanel Page2;
    private javax.swing.JLabel Page2verse;
    private javax.swing.JPanel Page3;
    private javax.swing.JLabel Page3verse;
    private javax.swing.JPanel Page4;
    private javax.swing.JLabel Page4verse;
    private javax.swing.JPanel Page5;
    private javax.swing.JLabel Page5verse;
    private javax.swing.JPanel Page6;
    private javax.swing.JLabel Page6verse;
    private javax.swing.JPanel Parent;
    private javax.swing.JButton Sixteento20;
    private javax.swing.JButton SixtoTen;
    private javax.swing.JButton Start;
    private javax.swing.JPanel StartPage;
    private javax.swing.JButton Twenty1to25;
    private javax.swing.JButton Twenty6to31;
    private javax.swing.JButton backToStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField p1Chapter;
    private javax.swing.JTextField p1Keyword;
    private javax.swing.JTextField p1Verse;
    private javax.swing.JTextField p2Chapter;
    private javax.swing.JTextField p2Keyword;
    private javax.swing.JTextField p2Verse;
    private javax.swing.JTextField p3Chapter;
    private javax.swing.JTextField p3Keyword;
    private javax.swing.JTextField p3Verse;
    private javax.swing.JTextField p4Chapter;
    private javax.swing.JTextField p4Keyword;
    private javax.swing.JTextField p4Verse;
    private javax.swing.JTextField p5Chapter;
    private javax.swing.JTextField p5Keyword;
    private javax.swing.JTextField p5Verse;
    private javax.swing.JTextField p6Chapter;
    private javax.swing.JTextField p6Keyword;
    private javax.swing.JTextField p6Verse;
    private javax.swing.JButton searchCV1;
    private javax.swing.JButton searchCV2;
    private javax.swing.JButton searchCV3;
    private javax.swing.JButton searchCV4;
    private javax.swing.JButton searchCV5;
    private javax.swing.JButton searchCV6;
    private javax.swing.JButton searchK1;
    private javax.swing.JButton searchK2;
    private javax.swing.JButton searchK3;
    private javax.swing.JButton searchK4;
    private javax.swing.JButton searchK5;
    private javax.swing.JButton searchK6;
    private javax.swing.JButton volOff;
    private javax.swing.JButton volOn;
    // End of variables declaration//GEN-END:variables
}
